Repository hakierspejs/statut, pull requests merged in 2020-10, with the labels that each got.

#21 Interpunkcja i literówki
  README.md
Labels: documentation, enhancement, good first issue, help wanted

#15 Zmiana i redakcja zwoływania Nadzwyczajnego Zebrania Walnego
  README.md
Labels: hacktoberfest-accepted

#11 Wywal aktywny udział jako kryterium uczestnictwa
  README.md
Labels: hacktoberfest-accepted

#13 Kadencja zarządu
  README.md
Labels: good first issue, hacktoberfest-accepted, question

#26 Skopiuj cele ze statutu HS Pomorze
  README.md
Labels: hacktoberfest-accepted

#30 Sposób zawiadamiania członków o walnym
  README.md
Labels: hacktoberfest-accepted

#32 przeredagowanie tekstu o nadzwyczajnym zdalnym
  README.md
Labels: hacktoberfest-accepted

#31 Przeniesienie maksymalnych kwot samodzielnie podejmowanego zobowiązan…
  README.md
Labels: hacktoberfest-accepted

#16 Termin walnego nazdzwyczajnego niewcześniejszy niż
  README.md
Labels: hacktoberfest-accepted, question
